name: Hourly Data Update 

on:
  schedule:
    - cron:  "* * * * *"

jobs: 
  update-data:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.0"

      - name: Install Packages Declated in DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Generate Data
        run: |
          source("R/1_Pull_Data.R")
        shell: Rscript {0}

      - name: Commit New Data Files
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -am "GitHub Action - Hourly Data Update - $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
